source "https://rubygems.org"

gem "fastlane", "=2.116.1"
gem "cocoapods", "=1.7.5"
gem 'gitlab', "=4.12.0"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
