source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'KwaiOpenSDKDemo' do
  
  pod 'KwaiSDK' ,'3.6.5'
  pod 'CTAssetsPickerController', '~> 3.3.2-alpha'
  
end
